datasource:
  mysql:
    validation-query: select 1
    driver: com.mysql.jdbc.Driver
    database: nojoke
    ip: localhost
    port: 3306
    username: root
    password: mysql.
    url: jdbc:mysql://${datasource.mysql.ip}:${datasource.mysql.port}/${datasource.mysql.database}?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
  redis:
    database: 0
    ip: localhost
    port: 6379
    password:
  druid:
    login-username: admin
    login-password: 123456